export const GET_EXERCISES = "GET_EXERCISES";
export const ADD_EXERCISE = "ADD_EXERCISE";
export const EMPTY_EXERCISES = "EMPTY_EXERCISES";
export const EDIT_EXERCISE = "EDIT_EXERCISE";
export const GET_EXERCISE = "GET_EXERCISE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
